# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Shitty Dev Notes'
tagline:          'Shitty Dev Notes'
description:      'Nothing to see here, human. Move along.'
url:              https://syfluqs.github.io
baseurl:          /

author:
  name:           'syfluqs'
  url:            https://github.com/syfluqs

paginate:         4

#image_optimzer config
# raw_images:       raw_img
# opt_images:       assets
# images_link:      assets
