# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            
tagline:          'Shitty Dev Notes'
description:      'Nothing to see here, human. Move Along.'
url:              https://syfluqs.github.io
baseurl:          /

author:
  name:           'syfluqs'
  url:            https://github.com/syfluqs

paginate:         5

# Jekyll options
# source :          ./src
# destination :     ./